/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ProfileLazyImport = createFileRoute('/profile')()
const IndexLazyImport = createFileRoute('/')()
const ManagementUsersLazyImport = createFileRoute('/management/users')()
const ManagementRolesLazyImport = createFileRoute('/management/roles')()

// Create/Update Routes

const ProfileLazyRoute = ProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ManagementUsersLazyRoute = ManagementUsersLazyImport.update({
  id: '/management/users',
  path: '/management/users',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/management/users.lazy').then((d) => d.Route),
)

const ManagementRolesLazyRoute = ManagementRolesLazyImport.update({
  id: '/management/roles',
  path: '/management/roles',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/management/roles.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/management/roles': {
      id: '/management/roles'
      path: '/management/roles'
      fullPath: '/management/roles'
      preLoaderRoute: typeof ManagementRolesLazyImport
      parentRoute: typeof rootRoute
    }
    '/management/users': {
      id: '/management/users'
      path: '/management/users'
      fullPath: '/management/users'
      preLoaderRoute: typeof ManagementUsersLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/management/roles': typeof ManagementRolesLazyRoute
  '/management/users': typeof ManagementUsersLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/management/roles': typeof ManagementRolesLazyRoute
  '/management/users': typeof ManagementUsersLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/management/roles': typeof ManagementRolesLazyRoute
  '/management/users': typeof ManagementUsersLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profile' | '/management/roles' | '/management/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile' | '/management/roles' | '/management/users'
  id: '__root__' | '/' | '/profile' | '/management/roles' | '/management/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  ManagementRolesLazyRoute: typeof ManagementRolesLazyRoute
  ManagementUsersLazyRoute: typeof ManagementUsersLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  ManagementRolesLazyRoute: ManagementRolesLazyRoute,
  ManagementUsersLazyRoute: ManagementUsersLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profile",
        "/management/roles",
        "/management/users"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/profile": {
      "filePath": "profile.lazy.tsx"
    },
    "/management/roles": {
      "filePath": "management/roles.lazy.tsx"
    },
    "/management/users": {
      "filePath": "management/users.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
